name: Deploy my-expense

on:
  push:
    branches:
      - main
  pull_request:
    types: [edited, synchronize]

jobs:
  deploy-react-to-gh-pages:
    runs-on: ubuntu-latest
    env:
      EXAMPLE: example # environment variable

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 20

      # - name: Cache dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build:client

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.NISHANT_LAB_GH_PAGE_DEPLOY_KEY }}
          external_repository: nishant-labs/nishant-labs.github.io
          publish_dir: ./client/dist
          destination_dir: my-expense
