name: Deploy Main

on:
  push:
    branches:
      - main

jobs:
  self-gh-pages:
    runs-on: ubuntu-latest
    env:
      EXAMPLE: example # environment variable
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build:client

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.NISHANT_LAB_GH_PAGE_DEPLOY_KEY }}
          external_repository: nishant-labs/nishant-labs.github.io
          publish_branch: main
          publish_dir: ./client/dist
          destination_dir: my-expense
