name: GH Deploy(gh-pages)

on:
  push:
    branches:
      - main

jobs:
  self-gh-pages:
    runs-on: ubuntu-latest
    env:
      EXAMPLE: example # environment variable
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build:client:gh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/dist
